export const Categories = [
    {
      name: 'Burger',
      image: require('../global/images/burger.png'),
      items: [
        {
          name: 'Classic Burger',
          weight: 120,
          rating: '5.0',
          price: 199,
          isTopOfTheWeek: true,
          image: require('../global/images/burger/classicburger.png'),
          size: 'Large 8"',
          crust: 'Thick Crust',
          delivery: 25,
          ingredients: [
            require('../global/images/flour.png'),
            require('../global/images/cheese.png'),
            require('../global/images/Sliced-Onion.png'),
            require('../global/images/Tomato.png'),
          ],
        },
        {
          name: 'Aloo Tikki Burger',
          weight: 150,
          rating: '4.5',
          price: 99,
          isTopOfTheWeek: false,
          image: require('../global/images/burger/alootikkiburger.png'),
          size: 'Large 12"',
          crust: 'Thick Crust',
          delivery: 20,
          ingredients: [
            require('../global/images/Sliced-Onion.png'),
            require('../global/images/Tomato.png'),
            require('../global/images/cheese.png'),
            require('../global/images/flour.png'),
          ],
        },
        {
          name: 'Biggie Cheese',
          weight: 250,
          rating: '4.2',
          price: 299,
          isTopOfTheWeek: false,
          image: require('../global/images/burger/biggiecheese.png'),
          size: 'Large 10"',
          crust: 'Thick Crust',
          delivery: 35,
          ingredients: [
            require('../global/images/Tomato.png'),
            require('../global/images/cheese.png'),
            require('../global/images/Sliced-Onion.png'),
            require('../global/images/flour.png'),
          ],
        },
      ],
    },
    {
      name: 'Pizza',
      image: require('../global/images/pizza.png'),
      items: [
        {
          name: 'Pepperoni Pizza',
          weight: 250,
          rating: '5.0',
          price: 199,
          isTopOfTheWeek: true,
          image: require('../global/images/pizza/pepperonipizza.png'),
          size: 'Large 14"',
          crust: 'Thin Crust',
          delivery: 30,
          ingredients: [
            require('../global/images/Tomato.png'),
            require('../global/images/cheese.png'),
            require('../global/images/Sliced-Onion.png'),
            require('../global/images/flour.png'),
          ],
        },
        {
          name: 'Plain Cheese Pizza',
          weight: 300,
          rating: '4.5',
          price: 299,
          isTopOfTheWeek: false,
          image: require('../global/images/pizza/plaincheesepizza.png'),
          size: 'Large 16"',
          crust: 'Thin Cheese',
          delivery: 25,
          ingredients: [
            require('../global/images/Sliced-Onion.png'),
            require('../global/images/flour.png'),
            require('../global/images/cheese.png'),
            require('../global/images/Tomato.png'),
          ],
        },
        {
          name: 'Mexican Green Wave',
          weight: 350,
          rating: '4.2',
          price: 499,
          isTopOfTheWeek: false,
          image: require('../global/images/pizza/mexicangreenwave.png'),
          size: 'Large 15"',
          crust: 'Thin Crust',
          delivery: 45,
          ingredients: [
            require('../global/images/flour.png'),
            require('../global/images/cheese.png'),
            require('../global/images/Tomato.png'),
            require('../global/images/Sliced-Onion.png'),
          ],
        },
      ],
    },
    {
      name: 'Soft Drinks',
      image: require('../global/images/softdrinks.png'),
      items: [
        {
          name: 'Coco Cola',
          weight: 200,
          rating: '5.0',
          price: 299,
          isTopOfTheWeek: true,
          image: require('../global/images/softdrinks/cocacola.png'),
          size: 'Medium Glass',
          crust: 'Small Ice',
          delivery: 10,
          ingredients: [require('../global/images/softdrinks/cocacola.png')],
        },
        {
          name: 'Orange Juice',
          weight: 500,
          rating: '4.5',
          price: 199,
          isTopOfTheWeek: false,
          image: require('../global/images/softdrinks/orange.png'),
          size: 'LArge Glass',
          crust: 'Large Ice',
          delivery: 8,
          ingredients: [require('../global/images/softdrinks/orange.png')],
        },
        {
          name: 'Mango Juice',
          weight: 150,
          rating: '4.2',
          price: 99,
          isTopOfTheWeek: false,
          image: require('../global/images/softdrinks/mango.png'),
          size: 'Large Glass',
          crust: 'Small Ice',
          delivery: 5,
          ingredients: [require('../global/images/softdrinks/mango.png')],
        },
      ],
    },
  ];